# Faster-rcnn config, explanation of settings in frameworks/faster-rcnn/lib/fast_rcnn/config.py
CUSTOM_ANCHORS: True
# DEDUP_BOXES: 0.125
TRAIN:
  SCALES: [1184, ]  # (368, 544, 736, 1104), orig: 600       [400, 500, 600, 700]
  MAX_SIZE: 1644 # 1536, 1056, orig: 1000
  IMS_PER_BATCH: 1
  #BATCH_SIZE: 128
  #FG_FRACTION: 0.25
  #FG_THRESH: 0.5
  #BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0.0
  #USE_FLIPPED: True
  #BBOX_REG: True
  #BBOX_THRESH: 0.5
  SNAPSHOT_ITERS: 10000
  #SNAPSHOT_INFIX: ''
  #USE_PREFETCH: False
  #BBOX_NORMALIZE_TARGETS: True
  #BBOX_INSIDE_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  #BBOX_NORMALIZE_MEANS: (0.0, 0.0, 0.0, 0.0)
  #BBOX_NORMALIZE_STDS: (0.1, 0.1, 0.2, 0.2)
  PROPOSAL_METHOD: 'gt'
  #ASPECT_GROUPING: False
  HAS_RPN: True # orig: False
  #RPN_POSITIVE_OVERLAP: 0.7
  #RPN_NEGATIVE_OVERLAP: 0.3
  #RPN_CLOBBER_POSITIVES: False
  #RPN_FG_FRACTION: 0.5
  #RPN_BATCHSIZE: 256
  #RPN_NMS_THRESH: 0.7
  #RPN_PRE_NMS_TOP_N: 12000
  #RPN_POST_NMS_TOP_N: 2000
  # RPN_MIN_SIZE: 20
  #RPN_BBOX_INSIDE_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
  #RPN_POSITIVE_WEIGHT: -1.0
  #USE_OHEM: True
  #OHEM_USE_NMS: True
  #OHEM_NMS_THRESH: 0.7
TEST:
  SCALES: [1184, ]
  MAX_SIZE: 1644
  #NMS_THRESH: 0.3
  #SVM: False
  #BBOX_REG: True
  HAS_RPN: True
  PROPOSAL_METHOD: 'gt'
  #RPN_NMS_THRESH: 0.7
  #RPN_PRE_NMS_TOP_N: 6000
  #RPN_POST_NMS_TOP_N: 300
  # RPN_MIN_SIZE: 20
