# Faster-rcnn config, explanation of settings in frameworks/faster-rcnn/lib/fast_rcnn/config.py
# CUSTOM_ANCHORS: True
TRAIN:
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
#  RPN_MIN_SIZE: 20
TEST:
  HAS_RPN: True
